version: '3'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
  user-db:
    image: postgres
  gdpr-db:
    image: postgres
  user-gdpr-cqrs-db:
    image: postgres
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
  gdpr-service:
    build: ./gdpr-service
    ports:
      - "8081:8080"
  user-gdpr-service:
    build: ./user-gdpr-service
    ports:
      - "8082:8080"
  user-gdpr-cqrs-service:
    build: ./user-gdpr-cqrs
    ports:
      - "8083:8080"
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
  admin-server:
    build: ./admin-server
    ports:
      - "9080:8080"
